logo: AHMED'S RESUME
title: Ahmed world is a portfolio site
email: youremail@mail.com
start_year: 2023
current_year: { { site.time | date: "%Y" } }
description:

baseurl: /ahmedsharifkhan
url: https://ahmedsharifkhan.github.io

facebook_username: https://www.facebook.com/ahmedsharifkhannoor
twitter_username: https://www.twitter.com/maxnoor87
instagram_username: https://www.instagram.com/ahmedsharifkhannoor
linkedin_username: https://www.linkedin.com/in/ahmedsharifkhannoor
github_username: https://www.github.com/ahmedsharifkhan
youtube_username: https://www.youtube.com/channel/UCBfIS1RdIpSoS1e75LXJuxw

# Build settings
theme: minima
plugins:
  - jekyll-feed
  - jekyll-sitemap


# defaults:
# - scope:
#     path: ""
# type: "posts"
# values:
#   permalink: "/blog/:title/"

# header_pages:
# - title: Home
#   url: /
# - title: Blog
#   url: /blog

host: 0.0.0.0
port: 4000
